version: '3.9'

services:
 mysql:
    profiles: ["deployment"]
    image: mysql:8.0.15
    ports:
        - "3306:3306"
    volumes:
       - ./database-scripts:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: kafkaFhirDemoDb
        MYSQL_USER: lfhuser
        MYSQL_PASSWORD: changePassword
