SET FOREIGN_KEY_CHECKS=0;
START TRANSACTION;

ALTER TABLE `CPTEVENTS` ADD FULLTEXT KEY `DESCRIPTION_2` (`DESCRIPTION`);

ALTER TABLE `DRGCODES` ADD FULLTEXT KEY `DESCRIPTION` (`DESCRIPTION`);

ALTER TABLE `echo_reports` ADD FULLTEXT KEY `TEXT` (`TEXT`);
ALTER TABLE `echo_reports` ADD FULLTEXT KEY `Impression` (`Impression`);

ALTER TABLE `ekg_reports` ADD FULLTEXT KEY `TEXT` (`TEXT`);

ALTER TABLE `medication_adverse_event` ADD FULLTEXT KEY `ade_span` (`ade_span`);

ALTER TABLE `microbiology_reports` ADD FULLTEXT KEY `TEXT` (`TEXT`);

ALTER TABLE `noteevents` ADD FULLTEXT KEY `TEXT` (`TEXT`);

ALTER TABLE `radiology_reports` ADD FULLTEXT KEY `Impression` (`Impression`);

ALTER TABLE `social_history` ADD FULLTEXT KEY `text` (`text`);


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


ALTER TABLE `CALLOUT`
  ADD CONSTRAINT `callout_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`);

ALTER TABLE `CPTEVENTS`
  ADD CONSTRAINT `cptevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `cptevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `DATETIMEEVENTS`
  ADD CONSTRAINT `datetimeevents_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `datetimeevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `datetimeevents_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `datetimeevents_fk_itemid` FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS` (`ITEMID`);

ALTER TABLE `DIAGNOSES_ICD`
  ADD CONSTRAINT `diagnoses_icd_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`);

ALTER TABLE `DRGCODES`
  ADD CONSTRAINT `drgcodes_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `drgcodes_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `eligibility_request`
  ADD CONSTRAINT `eligibility_request_ibfk_1` FOREIGN KEY (`payer_id`) REFERENCES `payer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `eligibility_request_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `PATIENTS` (`ROW_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `eligibility_request_response`
  ADD CONSTRAINT `eligibility_request_response_ibfk_1` FOREIGN KEY (`payer_id`) REFERENCES `payer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `eligibility_request_response_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `PATIENTS` (`ROW_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `eligibility_request_response_ibfk_3` FOREIGN KEY (`eligibility_request_id`) REFERENCES `eligibility_request` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `ICUSTAYS`
  ADD CONSTRAINT `icustays_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `icustays_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `INPUTEVENTS_CV`
  ADD CONSTRAINT `inputevents_cv_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `inputevents_cv_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `inputevents_cv_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`);

ALTER TABLE `INPUTEVENTS_MV`
  ADD CONSTRAINT `inputevents_mv_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `inputevents_mv_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `inputevents_mv_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`);

ALTER TABLE `LABEVENTS`
  ADD CONSTRAINT `labevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `labevents_fk_itemid` FOREIGN KEY (`ITEMID`) REFERENCES `D_LABITEMS` (`ITEMID`),
  ADD CONSTRAINT `labevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `MICROBIOLOGYEVENTS`
  ADD CONSTRAINT `microbiologyevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`);

ALTER TABLE `noteevents`
  ADD CONSTRAINT `noteevents_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `noteevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `noteevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `OUTPUTEVENTS`
  ADD CONSTRAINT `outputevents_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `outputevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `outputevents_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`);

ALTER TABLE `PATIENTS`
  ADD CONSTRAINT `patients_ibfk_1` FOREIGN KEY (`payer_id`) REFERENCES `payer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `patient_coverage`
  ADD CONSTRAINT `patient_coverage_ibfk_1` FOREIGN KEY (`payer_id`) REFERENCES `payer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `patient_coverage_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `PATIENTS` (`ROW_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `PRESCRIPTIONS`
  ADD CONSTRAINT `prescriptions_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `prescriptions_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `prescriptions_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `PROCEDUREEVENTS_MV`
  ADD CONSTRAINT `procedureevents_mv_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `procedureevents_mv_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `procedureevents_mv_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `procedureevents_mv_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `PROCEDURES_ICD`
  ADD CONSTRAINT `procedures_icd_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`);

ALTER TABLE `SERVICES`
  ADD CONSTRAINT `services_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`);

ALTER TABLE `TRANSFERS`
  ADD CONSTRAINT `transfers_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `transfers_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`);


SET FOREIGN_KEY_CHECKS=1;
COMMIT;
